name: Testing API
on: [push, pull_request]
jobs:
  testing_api:
    runs-on: ubuntu-latest
    env: 
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install -r requirements_test.txt
          pip install dvc[gs]==0.9.4
          pip install --upgrade google-cloud-storage
      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl model-track 
          pytest tests.py