name: Testing API
on: [push, pull_request]
jobs:
  testing_api:
    runs-on: ubuntu-latest
    env: 
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          wget https://github.com/libgit2/libgit2/archive/refs/tags/v1.5.0.tar.gz -O libgit2-1.5.0.tar.gz
          tar xzf libgit2-1.5.0.tar.gz
          cd libgit2-1.5.0/
          cmake .
          make
          sudo make install
          pip install pygit2
          pip install pyOpenSSL --upgrade
          pip install dvc[gs]
          pip install -r requirements_test.txt
      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-track 
          pytest tests.py